rename sample files once unzipped
Shopify/slate-cli pull request #132
Opened 2017-06-16 18:49 UTC by NathanPJF

### What are you trying to accomplish with this PR?

Companion piece to this PR in `slate`: https://github.com/Shopify/slate/pull/179

The idea: After running `slate theme`, you are given an unzipped `slate-src.zip` plus two files `config-sample` and `.gitignore-sample`.  Let's save the manual effort of renaming both these files when you start off.

### Checklist
For contributors:
- [ ] I have updated the documentation in the [README file](https://github.com/Shopify/slate-cli/blob/master/README.md) to reflect these changes, if applicable.

For maintainers:
- [ ] I have :tophat:'d these changes.
- [ ] I have bumped the `package.json` version in a separate PR, if applicable.

Considerations:
- [ ] These changes will require the [public Slate docs](https://shopify.github.io/slate/) to be updated.  See the [Shopify/slate repo](https://github.com/Shopify/slate/blob/master/CONTRIBUTING.md#documentation) for notes on updating docs, if applicable.

2017-06-16 19:10 UTC, chrisberthe requested changes

2017-06-16 19:10 UTC, chrisberthe commented on src/utils.js
> +  rename(current, target, (err) => {
Should we be wrapping this in `return new Promise((resolve, reject) => {});`?

2017-06-16 19:10 UTC, chrisberthe commented on src/utils.js
> +      throw err;
If so, `reject(err)` here. And `resolve()` outside of the condition.

2017-06-16 21:50 UTC, NathanPJF commented
New project... that fyre. 🔥 

![](http://take.ms/MqlL2)

2017-06-16 22:24 UTC, NathanPJF commented on src/commands/theme.js
> -            console.log(`  Renaming ${oldFile} to ${newFile}...`);
Decided I didn't like the message after it said "you're done".

![](http://take.ms/0AiaFx)

2017-06-19 19:19 UTC, chrisberthe commented on src/commands/theme.js
> -            console.log(`  Renaming ${oldFile} to ${newFile}...`);
Good call removing this.

2017-06-19 19:22 UTC, chrisberthe approved these changes

2017-06-19 19:22 UTC, chrisberthe commented on src/commands/theme.js
> +          function renamePromiseFactory({oldFile, newFile, dir}) {
Thanks for this ES6 lesson 🥇

2017-06-19 21:59 UTC, merged